stages:
  - build
  - deploy

compile-producer:
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:multistage -f Dockerfile.multistage .
    - docker push $CI_REGISTRY_IMAGE:multistage

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
